db_test = [
    {
        "id": 1,
        "name": "charger1",
        "number": 1305,
        "model": "Charger1",
        "location": "Location 1",
        "company": "Company1",
        "status": "offline",
    },
    {
        "id": 2,
        "name": "charger2",
        "number": 2310,
        "model": "Charger2",
        "location": "Location 2",
        "company": "Company2",
        "status": "online",
    },
    {
        "id": 3,
        "name": "charger3",
        "number": 3315,
        "model": "Charger3",
        "location": "Location 3",
        "company": "Company3",
        "status": "offline",
    },
    {
        "id": 4,
        "name": "charger4",
        "number": 4320,
        "model": "Charger4",
        "location": "Location 4",
        "company": "Company4",
        "status": "online",
    },
    {
        "id": 5,
        "name": "charger5",
        "number": 5325,
        "model": "Charger5",
        "location": "Location 5",
        "company": "Company5",
        "status": "offline",
    },
    {
        "id": 6,
        "name": "charger6",
        "number": 6330,
        "model": "Charger6",
        "location": "Location 6",
        "company": "Company6",
        "status": "online",
    },
    {
        "id": 7,
        "name": "charger7",
        "number": 7335,
        "model": "Charger7",
        "location": "Location 7",
        "company": "Company7",
        "status": "offline",
    },
    {
        "id": 8,
        "name": "charger8",
        "number": 8340,
        "model": "Charger8",
        "location": "Location 8",
        "company": "Company8",
        "status": "online",
    },
    {
        "id": 9,
        "name": "charger9",
        "number": 9345,
        "model": "Charger9",
        "location": "Location 9",
        "company": "Company9",
        "status": "offline",
    },
    {
        "id": 10,
        "name": "charger10",
        "number": 10350,
        "model": "Charger10",
        "location": "Location 10",
        "company": "Company10",
        "status": "online",
    },
    {
        "id": 11,
        "name": "charger11",
        "number": 11355,
        "model": "Charger11",
        "location": "Location 11",
        "company": "Company11",
        "status": "offline",
    },
    {
        "id": 12,
        "name": "charger12",
        "number": 12360,
        "model": "Charger12",
        "location": "Location 12",
        "company": "Company12",
        "status": "online",
    },
    {
        "id": 13,
        "name": "charger13",
        "number": 13365,
        "model": "Charger13",
        "location": "Location 13",
        "company": "Company13",
        "status": "offline",
    },
    {
        "id": 14,
        "name": "charger14",
        "number": 14370,
        "model": "Charger14",
        "location": "Location 14",
        "company": "Company14",
        "status": "online",
    },
    {
        "id": 15,
        "name": "charger15",
        "number": 15375,
        "model": "Charger15",
        "location": "Location 15",
        "company": "Company15",
        "status": "offline",
    },
    {
        "id": 16,
        "name": "charger16",
        "number": 16380,
        "model": "Charger16",
        "location": "Location 16",
        "company": "Company16",
        "status": "online",
    },
    {
        "id": 17,
        "name": "charger17",
        "number": 17385,
        "model": "Charger17",
        "location": "Location 17",
        "company": "Company17",
        "status": "offline",
    },
    {
        "id": 18,
        "name": "charger18",
        "number": 18390,
        "model": "Charger18",
        "location": "Location 18",
        "company": "Company18",
        "status": "online",
    },
    {
        "id": 19,
        "name": "charger19",
        "number": 19395,
        "model": "Charger19",
        "location": "Location 19",
        "company": "Company19",
        "status": "offline",
    },
    {
        "id": 20,
        "name": "charger20",
        "number": 20400,
        "model": "Charger20",
        "location": "Location 20",
        "company": "Company20",
        "status": "online",
    },
]


def append_data(data):
    db_test.append(data)
